# Copyright (c) 2024 iSoftStone Education Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

static_library("bathroom_safety") {
    sources = [
        "bathroom_safety.c",
        "lcd.c",
        "sht30.c",
        "mq2.c",
        "su_03t.c",
    ]

    include_dirs = [
        "//utils/native/lite/include",
        "//base/iot_hardware/peripheral/interfaces/kits",
        "//device/rockchip/rk2206/sdk_liteos/include",
        "//device/rockchip/rk2206/sdk_liteos/board/include",
        "//kernel/liteos_m/kernel/include",
        "//vendor/isoftstone/rk2206/samples/bathroom_safety",
    ]

    deps = [
        "//device/rockchip/hardware:hardware",
    ]
}